version: "3.8"

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1data:/data/db
    networks:
      - mongonet

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo2data:/data/db
    networks:
      - mongonet

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27019:27017"
    volumes:
      - mongo3data:/data/db
    networks:
      - mongonet


volumes:
  mongo1data:
  mongo2data:
  mongo3data:

networks:
  mongonet:
    driver: bridge